### ISSUE TITLE
多人的填报会出现网络错误的问题

### ISSUE THREAD

**Issue by cntommy** [MikasaEureka/BUPT_nCoV_easily_fixed_form#1]
想问一下填报多人的时候，第一个人能填报成功，第二个人就出现无法填报是什么原因呢
`2022-04-20 07:02:28,674 - INFO - auto.py:[12](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:12)1 - Start authorize for xxx ...
2022-04-20 07:02:31,517 - INFO - auto.py:[15](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:15)4 - Authorize successed !!!
2022-04-20 07:02:31,517 - INFO - auto.py:[16](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:16)0 - Start form ...
2022-04-20 07:02:31,518 - INFO - auto.py:[17](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:17)4 - Form: area: 北京市 海淀区, is in university: True
2022-04-20 07:02:31,783 - INFO - auto.py:[18](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:18)0 - Result below :
[20](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:20)22-04-20 07:02:31,783 - INFO - auto.py:181 - Responce: 今天已经填报了
2022-04-20 07:02:31,784 - INFO - auto.py:1[21](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:21) - Start authorize for xxx2 ...
20[22](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:22)-04-20 07:04:41,818 - ERROR - auto.py:185 - HTTPSConnectionPool(host='auth.bupt.edu.cn', port=443): Max retries exceeded with url: /authserver/login?service=https%3A%2F%2Fapp.bupt.edu.cn%2Fa_bupt%2Fapi%2Fsso%2Fcas%3Fredirect%3Dhttps%[25](https://github.com/cntommy/BUPT_nCoV_easily_fixed_form/runs/6090428227?check_suite_focus=true#step:5:25)3A%252F%252Fapp.bupt.edu.cn%252Fncov%252Fwap%252Fdefault%252Findex%26from%3Dwap (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0c28f9e070>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable`

**Comment by MikasaEureka** [comment]
抱歉，刚注意到，我看一下

**Comment by MikasaEureka** [comment]
标注一下修改参考
https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests
https://www.cnblogs.com/renjie1105/p/15162614.html
https://blog.csdn.net/lb245557472/article/details/80239603

采用增大时间间隔来处理
我设置1min以上的时间间隔，如果失败了你反馈给我

**Comment by MikasaEureka** [comment]
已经更新了，你测试一下反馈我结果

**Comment by cntommy** [comment]
> 已经更新了，你测试一下反馈我结果

应该没问题了 感激~
